"""
Optional HTTP API for Heritage Mini-LM (:8181).
Primary product chat remains Agent :8180; this exposes the trained mini LM directly.
"""
from __future__ import annotations

import os
from typing import Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from infer import answer_heritage, load_bundle

PORT = int(os.getenv("HERITAGE_LM_PORT", "8181"))

app = FastAPI(title="Heritage Mini-LM", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatIn(BaseModel):
    query: Optional[str] = None
    message: Optional[str] = None


@app.on_event("startup")
def _warm():
    try:
        load_bundle()
        print("[heritage-lm] checkpoint loaded")
    except Exception as e:
        print(f"[heritage-lm] not trained yet: {e}")


@app.get("/api/health")
def health():
    from pathlib import Path

    ckpt = Path(__file__).resolve().parent / "checkpoints" / "heritage_minigpt.pt"
    ready = ckpt.exists()
    meta = {}
    if ready:
        try:
            meta = load_bundle()["meta"]
        except Exception:
            pass
    return {
        "status": "ok" if ready else "untrained",
        "backend": "heritage-minigpt",
        "ready": ready,
        "meta": meta,
        "note": "Small domain LM trained on curated heritage corpus — not a frontier chat model.",
    }


@app.post("/api/chat")
def chat(body: ChatIn):
    q = (body.query or body.message or "").strip()
    if not q:
        return {"error": "query required", "ok": False}
    out = answer_heritage(q)
    return {
        "ok": out.get("ok", False),
        "answer": out.get("answer"),
        "error": out.get("error"),
        "mode": "heritage-minigpt",
        "backend": "heritage-minigpt",
        "confidence": 0.55 if out.get("ok") else 0.0,
        "agentsUsed": ["heritage-minigpt"],
        "reasoning": "Generated by the project MiniGPT trained on heritage dossiers (+ optional Wiki extracts).",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("server:app", host="0.0.0.0", port=PORT, reload=False)
